service: portfolio

plugins:
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs8.10
  stage: "${env:ENVIRONMENT}"
  region: eu-west-1
  environment:
      EMAIL: "${env:EMAIL}"
      DOMAIN: "${env:DOMAIN}"
  iamRoleStatements:
    - Effect: "Allow"
      Action: "ses:SendEmail"
      Resource: "*"

functions:
  send:
    name: "${self:service}-send-email-${self:provider.stage}"
    handler: handler.send
    events:
      - http:
          path: email/send
          method: post
          cors: true
